files:
  include: 'styleguide/**/*.scss'
  ignore:
    - 'styleguide/_sass/_rsweb-font-style.scss'
    - 'styleguide/_sass/_syntax-highlighting.scss'
    - 'styleguide/_themes/derek/scss/components/_rsweb-font-style.scss'
    - 'styleguide/_themes/global/scss/_bootstrap_variables.scss'
    - 'styleguide/_themes/global/scss/_bootstrap_overrides.scss'
    - 'styleguide/_themes/global/scss/mixins/*.scss'
rules:
  no-url-protocols: 0
  class-name-format:
    - 1
    - convention: ^([a-z0-9]+([A-Z][a-z0-9]+)*)(-{1}([a-z0-9]+([A-Z][a-z0-9]+)*)){0,2}$
    - convention-explanation: 'Classes should be camelCase and separated by no more than 2 hyphens'
